variables:
  - &alpine_image 'alpine:3.22.4'
  - &build_image 'opencloudeu/desktop-client-build:ubuntu-24.04-qt6.10'
  - &minio_image 'quay.io/opencloudeu/minio-mc-ci:1.0'
  - &minio_environment
    AWS_ACCESS_KEY_ID:
      from_secret: cache_s3_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_s3_secret_key
    CACHE_BUCKET:
      from_secret: cache_s3_bucket
    MC_HOST: 'https://s3.ci.opencloud.eu'
  - &trigger_path
    include:
      - test/gui/**
      - src/**
      - cmake/**
      - THEME.cmake
      - VERSION.cmake
      - CMakeLists.txt
      - OPENCLOUD.cmake
      - .woodpecker/**
    exclude:
      - .woodpecker/ready-release-go.yaml
      - .woodpecker/translation.yaml
      - test/gui/manual-test-plan

when:
  - branch:
      - main
      - stable-*
    event:
      - push
      - manual
    path:
      <<: *trigger_path
  - event: pull_request
    path:
      <<: *trigger_path
    evaluate: |
      !(CI_COMMIT_SOURCE_BRANCH matches "next-release/(main|stable-*)" && CI_COMMIT_AUTHOR == "openclouders")
  - event: tag
  - event: cron
    cron: nightly*

workspace:
  base: /woodpecker/
  path: desktop

steps:
  - name: fix-permissions
    image: *alpine_image
    commands:
      - chmod o+w $CI_WORKSPACE/ -R

  - name: build-client-for-ui-tests
    image: *build_image
    pull: true # remove this once the nightlies run with the new build image
    commands:
      - mkdir -p build
      - cd build
      - cmake -GNinja -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -S ..
      - ninja

  - name: upload-desktop-client-cache
    image: *minio_image
    environment:
      <<: *minio_environment
    commands:
      - mc alias set s3 $MC_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -a -r $CI_WORKSPACE/build/bin s3/$CACHE_BUCKET/desktop/client-build/${CI_COMMIT_SHA}/
      - mc ls --recursive s3/$CACHE_BUCKET/desktop/client-build
