[GeneralSettings]
# creating cache files on github makes no sense
Packager/CreateCache = False

Paths/CCACHE_DIR = ${Env:HOME}/ccache
Compile/UseCCache = True

CodeSigning/MacKeychainPath = ${Env:SIGNING_KEY_FILE_PATH}


[windows-cl-msvc2022-x86_64]
# used on Windows to work around long path issues. Should be the same as HOME
ShortPath/JunctionDir = ${Env:SYSTEMDRIVE}/_
CodeSigning/CommonName = Test certificate for 'OpenCloud Desktop Client [OSS]'
CodeSigning/WindowsCustomSignCommand = pwsh -File "${Env:GITHUB_WORKSPACE}/.github/workflows/.signpath.ps1" -F "%F"

[macos-clang-x86_64]
Packager/PackageType = MacPkgPackager

[macos-clang-arm64]
Packager/PackageType = MacPkgPackager

[linux-gcc-x86_64]
Environment/SourceCommand = export PKG_CONFIG_PATH=(/usr/bin/pkg-config --variable pc_path pkg-config) && source /opt/rh/gcc-toolset-14/enable

[linux-gcc-x86_64-debug]
Environment/SourceCommand = export PKG_CONFIG_PATH=(/usr/bin/pkg-config --variable pc_path pkg-config) && source /opt/rh/gcc-toolset-14/enable
