name: OpenCloud Desktop CI

on:
  push:
    branches:
      - main
      - 'stable-[0-9]+.[0-9]+'
      - 'stable-[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:
    inputs:
      releaseChannel:
        description: 'The release channel'
        required: true
        default: 'stable'
        type: choice
        options:
          - stable
          - beta
  schedule:
    - cron: '11 3 * * 1-5'
      timezone: "Europe/Berlin"

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: pwsh

jobs:
# ------------------------------------------------------------------------------------------------------------------------------------------
  build:
    permissions:
      # actions/upload-artifact doesn't need contents: write
      contents: read
      actions: read
      security-events: write
    strategy:
        fail-fast: true
        matrix:
            include:
            - target: windows-cl-msvc2022-x86_64
              os: windows-2022
              clang_tidy: false
              container:
              signing:
                # set the yaml anchor signing_enabled to true if the workflow was triggered by
                # a workflow_dispatch against main, stable-*, or tags
                enabled: &signing_enabled ${{
                    (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' )
                      && (            github.ref == 'refs/heads/main'
                        || startswith(github.ref,   'refs/heads/stable-')
                        || startswith(github.ref,   'refs/tags/')
                      )
                  }}
            - target: macos-clang-arm64
              os: macos-latest
              clang_tidy: false
              container:
              signing: &macos_signing
                enabled: *signing_enabled
                keyfile_secret_name: kv/data/signing/mac-keychain
                keyfile_secret_field: b64
                keyfile_file_path: /Users/runner
                keyfile_file_name: ci-signing.keychain-db
                passwords:
                  - secret_name: kv/data/signing/mac-keychain
                    secret_field: pw
                    env_name: CRAFT_SECRET_MAC_KEYCHAIN_PASSWORD
                  - secret_name: kv/data/signing/mac-keychain
                    secret_field: notarization_pw
                    env_name: CRAFT_SECRET_MAC_APP_PASSWORD
            - target: macos-clang-x86_64
              os: macos-latest
              clang_tidy: false
              container:
              signing: *macos_signing
            - target: linux-gcc-x86_64
              os: ubuntu-latest
              clang_tidy: true
              container: invent-registry.kde.org/sysadmin/ci-images/craft-appimage-alma9:latest

    name: ${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    environment:
      # set the environment name to main if signing has been enabled
      # the environment contains the required secrets for signing the packages
      name: ${{ matrix.signing.enabled && 'main' || '' }}
      deployment: false

    env:
      CRAFT_TARGET: ${{ matrix.target }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CRAFT_PACKAGE_SYMBOLS: ${{  github.event_name != 'pull_request' }}
      SIGN_PACKAGE: ${{ matrix.signing.enabled }}
      # set the signing key file path if signing is enabled and the keyfile is provided
      SIGNING_KEY_FILE_PATH: ${{
          matrix.signing.keyfile_file_path && matrix.signing.keyfile_file_name
          && format('{0}/{1}', matrix.signing.keyfile_file_path, matrix.signing.keyfile_file_name)
          || ''
        }}

    container: ${{ matrix.container }}

    steps:
    - name: Check out full source code for tooling
      if: ${{ matrix.target  == 'linux-gcc-x86_64' }}
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Check out latest commit
      if: ${{ matrix.target  != 'linux-gcc-x86_64' }}
      uses: actions/checkout@v7

    - name: Restore and update cache
      if: github.event_name != 'pull_request'
      uses: actions/cache@v6
      with:
        path: |
          ~/ccache
        key: ${{ runner.os }}-${{ matrix.target }}-${{ github.run_id }} # generate a new key every time to trigger an update
        restore-keys: ${{ runner.os }}-${{ matrix.target }}

    - name: Restore cache
      if: github.event_name == 'pull_request'
      uses: actions/cache/restore@v6
      with:
        path: |
          ~/ccache
        key: ${{ runner.os }}-${{ matrix.target }}

    - name: Clone CraftMaster
      run: |
        git clone --depth=1 https://invent.kde.org/kde/craftmaster.git "${home}/craft/CraftMaster/CraftMaster"

    - name: Craft setup
      run: |
        New-Item -Path ~/cache -ItemType Directory -ErrorAction SilentlyContinue
        # disable git's safe.directory
        git config --global --add safe.directory '*'
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" --setup

    - name: Craft unshelve
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --unshelve "${env:GITHUB_WORKSPACE}/.craft.shelf"
        # bootsrtap in case the shelf was empty
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c craft
        # ccache
        if (-not $IsWindows) {
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c dev-utils/ccache
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --run "ccache -M500MB"
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --run "ccache -s"
        }

    - name: Prepare
      run: |
        New-Item -ItemType Directory "${env:GITHUB_WORKSPACE}/binaries/"
        # settings
        if ("${{ github.ref_type }}" -ne "tag" -or "${{ inputs.releaseChannel }}" -eq "beta" ) {
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --set "forceAsserts=true" opencloud/opencloud-desktop
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --set "buildBeta=true" opencloud/opencloud-desktop
        }
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --set "srcDir=${env:GITHUB_WORKSPACE}" opencloud/opencloud-desktop
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --set "buildNumber=${{ github.run_number }}" opencloud/opencloud-desktop
        # optional deployment dependencies
        if ($IsWindows) {
            & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c dev-utils/nsis
        } elseif($IsLinux) {
            & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c dev-utils/linuxdeploy
            # ensure we have fuse3-devel installed
            dnf install -y fuse3-devel file
        } elseif($IsMacOS -and ${env:SIGN_PACKAGE} -ieq "true") {
            brew install packages
        }

    - name: Install dependencies
      run: |
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --install-deps opencloud/opencloud-desktop

    - name: QML format lint
      if: matrix.target  == 'linux-gcc-x86_64'
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c libs/qt6/qttools
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --run pwsh -c "git ls-files "*.qml" "*.js" "*.mjs" | %{ qmlformat -i `$_}"
        $diff = git diff
        if ($diff) {
          $diff
          exit 1
        }

    - name: clang-format format lint
      if: matrix.target  == 'linux-gcc-x86_64' && github.event_name == 'pull_request'
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c libs/llvm
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --run git clang-format --force  ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
        $diff = git diff
        if ($diff) {
          $diff
          exit 1
        }

    - name: Update Shelf
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --shelve "${env:GITHUB_WORKSPACE}/.craft.shelf"
        Copy-Item "${env:GITHUB_WORKSPACE}/.craft.shelf" "${env:GITHUB_WORKSPACE}/binaries/craft.shelf"

    - name: Build
      run: |
        if ("${{ matrix.target }}" -eq "macos-64-clang-debug" ) {
            # https://api.kde.org/ecm/module/ECMEnableSanitizers.html
            # address;leak;undefined
            # clang: error: unsupported option '-fsanitize=leak' for target 'x86_64-apple-darwin21.6.0'
            & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --set args="-DECM_ENABLE_SANITIZERS='address;undefined'" opencloud/opencloud-desktop
        }
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --no-cache opencloud/opencloud-desktop

    - name: Run tests
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --no-cache --test opencloud/opencloud-desktop

    - name: Clang tidy
      if: ${{ matrix.clang_tidy }}
      run: |
        cargo install clang-tidy-sarif sarif-fmt
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c libs/llvm dev-utils/clazy
        $env:BUILD_DIR = $(& "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --get buildDir -q opencloud/opencloud-desktop)
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --run pwsh "${env:GITHUB_WORKSPACE}/.github/workflows/.run-clang-tidy.ps1"

    - name: Upload SARIF file
      if: ${{ matrix.clang_tidy }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: clang-tidy.sarif

    - name: get signing key
      if: ${{ matrix.signing.enabled && matrix.signing.keyfile_secret_name != null }}
      id: signing-secrets
      uses: hashicorp/vault-action@v4
      with:
        url: ${{ secrets.BAO_URL }}
        method: userpass
        username: ${{ secrets.BAO_USERNAME }}
        password: ${{ secrets.BAO_PASSWORD }}
        exportEnv: false
        secrets: |
          ${{ matrix.signing.keyfile_secret_name }} ${{ matrix.signing.keyfile_secret_field }} | key_b64

    - name: Write signing keys to disk
      if: steps.signing-secrets.conclusion == 'success'
      env:
        SIGNING_KEY: ${{ steps.signing-secrets.outputs.key_b64 }}
      run: |
        $secretFile = Join-Path -Path "${{ matrix.signing.keyfile_file_path }}" -ChildPath "${{ matrix.signing.keyfile_file_name }}";
        $encodedBytes = [System.Convert]::FromBase64String($env:SIGNING_KEY);
        Set-Content $secretFile -Value $encodedBytes -AsByteStream;
        Get-FileHash $secretFile | Format-List

      # FixMe: add some sort of iteration to the secrets list
    - name: get signing key passwords
      if: matrix.signing.enabled && matrix.signing.passwords != null
      uses: hashicorp/vault-action@v4
      with:
        url: ${{ secrets.BAO_URL }}
        method: userpass
        username: ${{ secrets.BAO_USERNAME }}
        password: ${{ secrets.BAO_PASSWORD }}
        exportEnv: true
        secrets: |
          ${{ matrix.signing.passwords[0].secret_name }} ${{ matrix.signing.passwords[0].secret_field }} | ${{ matrix.signing.passwords[0].env_name }} ;
          ${{ matrix.signing.passwords[1].secret_name }} ${{ matrix.signing.passwords[1].secret_field }} | ${{ matrix.signing.passwords[1].env_name }}

    - name: Package
      # Package for linux. Package for mac only if signed
      if: ${{ github.event_name != 'pull_request' && (startsWith(matrix.target, 'linux') || (startsWith(matrix.target, 'macos') && steps.signing-secrets.conclusion == 'success')) }}
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --no-cache --package opencloud/opencloud-desktop

    - name: Package for testing
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        if ($isLinux) {
          # its always an appimage on linux
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --no-cache --package opencloud/opencloud-desktop
        } else {
          & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --no-cache --package --options "[Packager]PackageType=PortablePackager" opencloud/opencloud-desktop
        }

    - name: Prepare artifacts
      run: |
        Copy-Item "${home}/craft/binaries/*" "${env:GITHUB_WORKSPACE}/binaries/" -ErrorAction SilentlyContinue
        if ("${{ github.ref_type }}" -eq "tag"  ) {
          Get-ChildItem "${env:GITHUB_WORKSPACE}/binaries/" | ForEach-Object {
            $newName = $_.Name -replace "opencloud-desktop-HEAD-\d*-", "OpenCloud_Desktop-${{ github.ref_name }}-"
            if ($newName -ne $_.Name) {
              Move-Item -Path $_ -Destination (Join-Path $_.Directory $newName) -Force
            }
          }
        }

    - name: remove signing keys from disk
      if: steps.signing-secrets.conclusion == 'success' && always()
      run: |
        Remove-Item -force "${{ matrix.signing.keyfile_file_path }}\${{ matrix.signing.keyfile_file_name }}"

    - name: Package msix
      if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
      run: |
        & "${env:GITHUB_WORKSPACE}/.github/workflows/.craft.ps1" -c --no-cache --package --options "[Packager]PackageType=AppxPackager" --options "[Packager]Destination=${{ github.workspace }}/msix/" opencloud/opencloud-desktop
        Move-Item -Path "${{ github.workspace }}/msix/*.msix" -Destination "${{ github.workspace }}/msix/OpenCloud_Desktop-${{ github.run_number }}.msix" -Force

    - name: Upload binary artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-${{ github.run_number }}
        path: ${{ github.workspace }}/binaries/*

    - name: Upload store msix
      if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-store-msix-${{ github.run_number }}
        path: ${{ github.workspace }}/msix/*.msixupload
        archive: false

    - name: Upload unsigned msix
      id: upload-unsigned-artifact
      if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-msix-unsigned-temp-${{ github.run_number }}
        path: ${{ github.workspace }}/msix/*.msix

    - name: submit msix for signing
      id: submit-signing-request
      uses: signpath/github-action-submit-signing-request@v2
      if: ${{ matrix.signing.enabled && steps.upload-unsigned-artifact.conclusion == 'success' }}
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID }}'
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        project-slug: 'desktop'
        signing-policy-slug: 'test-signing'
        artifact-configuration-slug: 'deep_sign_msix_zip'
        output-artifact-directory: '${{ github.workspace }}/msix/'
        skip-decompress: false
        github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
        wait-for-completion: true

    - name: Upload signed msix
      id: upload-signed-artifact
      if: ${{ steps.submit-signing-request.conclusion == 'success' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-msix-${{ github.run_number }}
        path: ${{ github.workspace }}/msix/*.msix
        archive: false
